// Mocks generated by Mockito 5.3.2 from annotations
// in data_visualizer/test/features/parser/repository/las_parser.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:data_visualizer/features/term/repository/parser/las_parser.dart'
    as _i2;
import 'package:file_picker/file_picker.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ParserRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockParserRepositoryImpl extends _i1.Mock
    implements _i2.LasParser {
  MockParserRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String?> getNames(_i3.FilePickerResult? result) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTermNames,
          [result],
        ),
        returnValue: <String?>[],
      ) as List<String?>);
  @override
  List<DateTime> getTimes(_i3.FilePickerResult? result) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTermTimes,
          [result],
        ),
        returnValue: <DateTime>[],
      ) as List<DateTime>);
}
